### ISSUE TITLE
Update links to documentation in the README file

### ISSUE THREAD

**Issue by Saif807380** [preprocessy/preprocessy#131]
We have updated our documentation branches. We currently have 2 branches - latest which points to the main branch and 1.x.x which points the 1.x.x branch. There is no stable docs branch anymore. So the links in the README should point to the latest docs url.

**Comment by Aadityajoshi151** [comment]
Hi, I would like to work on this.
Just for clarification, I have to add the https://preprocessy.readthedocs.io/en/latest/ (latest link) to the "Documentation" and "Links" section of both the branches, right?

**Comment by Saif807380** [comment]
"Documentation" and "Changes" links. And create a PR just for the main branch.
