### ISSUE TITLE
Unit Tests required

### ISSUE THREAD

**Issue by Saif807380** [preprocessy/preprocessy#26]
Currently, there are no tests written for the following modules -

- [x] Input Module
- [x] Handling Null Values
- [x] Handling Outliers
- [x] Normalization and Scaling

Please follow the test naming convention so that `pytest` can run the tests.

**Comment by Bhumika-Kothwal** [comment]
I would like to contribute to solving this issue @Saif807380

**Comment by SaminaAttari786** [comment]
I want to work on this issue .

**Comment by Saif807380** [comment]
All tests for the respective modules have been added.
