### ISSUE TITLE
Implement one-hot encoding function as a custom user option

### ISSUE THREAD

**Issue by Priyesh1202** [preprocessy/preprocessy#32]
Another way to handle categorical data is by one-hot encoding . One hot encoding creates a new column for every entity in one categorical column and enters 1 if present in corresponding row of original column else 0 . Implement this from scratch by taking the user's option and also taking the column names which need to be one hot encoded as input. 

Follow the conventions for writing code and make changes in the comments of _categorical.py to include any new functions added.

**Comment by Bhumika-Kothwal** [comment]
I would like to contribute to solving this issue @Saif807380

**Comment by Saif807380** [comment]
Implemented in #48
