### ISSUE TITLE
Update tests to use to pytest parameterization

### ISSUE THREAD

**Issue by Saif807380** [preprocessy/preprocessy#42]
Currently, test cases that differ only in the inputs are defined as separate tests or using multiple `assert` statements. We can clean up the tests by using [pytest parameterization](https://docs.pytest.org/en/stable/parametrize.html). 

Also, tests are grouped together as classes. However, that's the `unittest` way of doing things. `pytest` doesn't care whether the tests are independent functions or part of classes. So maybe we can ditch the classes altogether.

**Comment by Bhumika-Kothwal** [comment]
I want to work on this issue
