### ISSUE TITLE
Refactor modules to support pipeline params

### ISSUE THREAD

**Issue by Saif807380** [preprocessy/preprocessy#43]
All the pipelines will inherit the `Base Pipeline` and hence have a similar structure and method of passing data from one function to the next. We need to update each of the functions to support this method of getting input as `params` dict and adding the output to the `params` dict as well.

List of modules to be updated - 

- [x] Input
- [x] Handle Null Values
- [x] Resampling
- [x] Outliers
- [x] Scaling
- [x] Encoding
- [x] Feature Selection

Just comment the name of the module that you want to work on and make a PR accordingly.

References - See test file for how the functions must be defined and will be used https://github.com/preprocessy/preprocessy/pull/38

**Comment by Bhumika-Kothwal** [comment]
I would like to work on Input module.

**Comment by DevayaniShivankar** [comment]
I'll work on outliers.

**Comment by Jhagrut** [comment]
i'll work on feature selection

**Comment by Bhumika-Kothwal** [comment]
I will work on encoding module.

**Comment by DevayaniShivankar** [comment]
I'll work on scaling module.

**Comment by Bhumika-Kothwal** [comment]
I will work on scaling module.

**Comment by Saif807380** [comment]
Great work everyone. Closing this issue as all tasks are completed. (#38, #45, #48, #49, #52, #53, #56)
